# -*- mode: ruby -*-
# vi: set ft=ruby :

require "../common/common"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # AWS provider overrides this:
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.synced_folder "../../protosite", "/site"

  config.vm.provider :aws do |aws, override|
    config.vm.box = "dummy"
    config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.keypair_name = 'qball'
    aws.region = "us-west-2"
    #aws.ami = "ami-7747d01e"
    #aws.ami = "ami-aa941e9a"
    aws.ami = "ami-70f96e40"
    aws.instance_type = "m1.medium"  
    aws.security_groups = [ 'quick-start-1' ]
    aws.tags = {
      'Name' => 'qball'
    }
    override.ssh.username = "ubuntu"  # AWS wants this
    override.ssh.private_key_path = ENV['HOME'] + "/.ssh/qball.pem"
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../manifests"
    puppet.options = "--verbose --debug"
    puppet.manifest_file  = "aws.pp"
  end

end

