# -*- mode: ruby -*-
# vi: set ft=ruby :

require "../common/common"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # AWS provider overrides this:
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.synced_folder "../../protosite", "/site"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider :virtualbox do |vb, override|
    # Don't boot with headless mode
    #vb.gui = true
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../manifests"
    puppet.options = "--verbose --debug"
    puppet.manifest_file  = "vbox.pp"
  end

end
